"""empty message

Revision ID: 0414ad48ba86
Revises: 
Create Date: 2022-04-06 20:55:28.215828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0414ad48ba86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=30), nullable=True),
    sa.Column('local_name', sa.String(length=50), nullable=True),
    sa.Column('type_of_event', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('place', sa.String(length=30), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('parking', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('cover', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('type_of_user', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###
