"""empty message

Revision ID: 1f9cf914fa58
Revises: 84c260108513
Create Date: 2022-03-30 14:13:30.122137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9cf914fa58'
down_revision = '84c260108513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_time', sa.String(length=10), nullable=True))
    op.add_column('event', sa.Column('end_time', sa.String(length=10), nullable=True))
    op.add_column('event', sa.Column('email', sa.String(length=50), nullable=True))
    op.drop_column('event', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('schedule', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('event', 'email')
    op.drop_column('event', 'end_time')
    op.drop_column('event', 'start_time')
    # ### end Alembic commands ###
