"""empty message

Revision ID: 84c260108513
Revises: 6d50e54595c6
Create Date: 2022-03-29 00:25:34.198261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c260108513'
down_revision = '6d50e54595c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=30), nullable=True),
    sa.Column('local_name', sa.String(length=50), nullable=True),
    sa.Column('type_of_event', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('place', sa.String(length=30), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('schedule', sa.String(length=30), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('parking', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('cover', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
